"""add reflection entry fields

Revision ID: 01dab14481e3
Revises: 51bf417cc5bf
Create Date: 2026-08-02 22:18:37.557518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01dab14481e3'
down_revision: Union[str, Sequence[str], None] = '51bf417cc5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reflection_entries', sa.Column('user_language', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    op.add_column('reflection_entries', sa.Column('related_slogans', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    op.add_column('reflection_entries', sa.Column('growth_direction', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reflection_entries', 'growth_direction')
    op.drop_column('reflection_entries', 'related_slogans')
    op.drop_column('reflection_entries', 'user_language')
    # ### end Alembic commands ###