"""add reflection entries and embeddings

Revision ID: 4000283877ad
Revises: 
Create Date: 2026-07-27 22:44:33.245210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '4000283877ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflection_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('emotions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('patterns', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('contexts', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('core_principles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('memo_interpretation', sa.Text(), nullable=False),
    sa.Column('conversation_guidance', sa.Text(), nullable=False),
    sa.Column('safety', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflection_embeddings',
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['reflection_entries.id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reflection_embeddings')
    op.drop_table('reflection_entries')
    # ### end Alembic commands ###
