"""add slogan number

Revision ID: 51bf417cc5bf
Revises: 6bd87622f15e
Create Date: 2026-07-29 21:19:33.318902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bf417cc5bf'
down_revision: Union[str, Sequence[str], None] = '6bd87622f15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reflection_entries', sa.Column('slogan_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reflection_entries', 'slogan_number')
    # ### end Alembic commands ###
