"""add point to reflection entries

Revision ID: 99a242e25f3b
Revises: 4000283877ad
Create Date: 2026-07-28 21:19:06.098676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a242e25f3b'
down_revision: Union[str, Sequence[str], None] = '4000283877ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reflection_entries', sa.Column('point', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reflection_entries', 'point')
    # ### end Alembic commands ###
